[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "arxivbot"
authors = [{ name = "Anil Keshwani", email = "anilkeshwani@hotmail.com" }]
description = "A minimal arXiv clipper"
license = { file = "LICENSE" }
requires-python = ">=3.9"
dynamic = ["dependencies", "version", "readme"]

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }
readme = { file = ["README.rst"] }

[tool.setuptools_scm]

[project.scripts]
obsidian-import = "arxivbot.obsidian_importer:main"
